- src:
  - src
  - tests
  - app

  line_limit: 100

  extensions:
  - OverloadedStrings
  - NoImplicitPrelude
  - TypeApplications
  - DeriveGeneric
  - DeriveAnyClass
  - RecordWildCards
  - ScopedTypeVariables
  - LambdaCase
