name:                hext
version:             0.1.0.0
github:              "ilyakooo0/hext"
license:             Unlicense
author:              "iko"
maintainer:          "ilyakooo0@gmail.com"
copyright:           "2019 Ilya Kostyuchenko"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ilyakooo0/hext#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec
- relude
- yaml
- aeson
- aeson-casing
- optparse-applicative
- directory-tree
- scientific
- text

library:
  source-dirs: src

executables:
  hext:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hext

tests:
  hext-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hext
